### ISSUE TITLE
Can't execute two commands at once (Threads)

### ISSUE THREAD

**Issue by V35HR4J** [V35HR4J/Automate-Telegram#6]
Todo: Make second command work without waiting for first one to finish.

**Comment by jainamoswal** [comment]
I would like to fix this if no one is working in it

**Comment by V35HR4J** [comment]
Hi, @jainamoswal feel free to send PR 😇💜

**Comment by jainamoswal** [comment]
Would that be okay if I change the library used here ? 
`python-telegram-bot` to `pyrogram` (or any other MTProto libraries)

**Comment by V35HR4J** [comment]
Closing this issue as https://github.com/V35HR4J/Automate-Telegram/pull/11 fixed it.
All thanks to @Sankalpa-Acharya
